<?php

namespace Coachella\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LayoutsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayoutsRepository extends EntityRepository
{
}