<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CoachellaUserBundleEntityDataProxy extends \Coachella\UserBundle\Entity\Data implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setData($data)
    {
        $this->__load();
        return parent::setData($data);
    }

    public function getData()
    {
        $this->__load();
        return parent::getData();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setLayout(\Coachella\UserBundle\Entity\Layouts $layout)
    {
        $this->__load();
        return parent::setLayout($layout);
    }

    public function getLayout()
    {
        $this->__load();
        return parent::getLayout();
    }

    public function addLayouts(\Coachella\UserBundle\Entity\Layouts $layout)
    {
        $this->__load();
        return parent::addLayouts($layout);
    }

    public function setLayoutId($layoutId)
    {
        $this->__load();
        return parent::setLayoutId($layoutId);
    }

    public function getLayoutId()
    {
        $this->__load();
        return parent::getLayoutId();
    }

    public function setLayouts(\Coachella\UserBundle\Entity\Layouts $layouts)
    {
        $this->__load();
        return parent::setLayouts($layouts);
    }

    public function getLayouts()
    {
        $this->__load();
        return parent::getLayouts();
    }

    public function setCheckout(\Coachella\UserBundle\Entity\Layouts $checkout)
    {
        $this->__load();
        return parent::setCheckout($checkout);
    }

    public function getCheckout()
    {
        $this->__load();
        return parent::getCheckout();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'data', 'layout_id', 'type');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}